### ISSUE TITLE
Support ` for fenced code blocks

### ISSUE THREAD

**Issue by bootstraponline** [toptensoftware/markdowndeep#19]
It looks like markdowndeep treats `~` as the exclusive fenced code block character. It'd be nice to support ` as well.

``````
```
one

two

three
```
``````

Produces

``````
"<p><code>one

two

three
</code></p>
<p>two</p>
<p>three
```</p>
``````

Expected

```
"<p><code>one

two

three
</code></p>
```

**Comment by borekb** [comment]
For some reason, `~~~` works for me while ``` doesn't. What can it be?
