### ISSUE TITLE
Multiple markdowndeep editors on the same page

### ISSUE THREAD

**Issue by Danthar** [toptensoftware/markdowndeep#38]
Currently this is working however the preview pane is not, this is because of a bug in how getting the Preview div is handled.

It fails because it uses a global selector to retrieve the preview div. This is obviously done to maximise the flexibility one has as to where to display the preview div. 

However its not very accommodating when you want to display multiple editors on the same page.

**Comment by PeterSawyer** [comment]
Thanks this worked for me too. :+1:   Great tool.
